title: Rajeev Atla
author:
  name: Rajeev Atla
  email: rajeev.atla@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  A budding physicist with interests in software architecture, finance, and entrepreneurship.

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # twitter: 
    github:  RajeevAtla
    # devto: 
    # dribbble: 
    # facebook: 
    # flickr:  
    instagram: rat.la
    linkedin: Rajeev Atla
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # keybase: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

    # GitLab instances
    # gitlab:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
