title: Rajeev Atla
author:
  name: Rajeev Atla
  email: rajeev@rajeevatla.com
description: > # this means to ignore newlines until "show_excerpts:"
  My old blog
url: "https://rajeevatla.github.io/blog"

show_excerpts: true # set to true to show excerpts on the homepage

# incremental: true # set to true to rebuild only updated pages

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: rajeevatla

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # twitter: 
    github:  RajeevAtla
    # devto: 
    # dribbble:
    linkedin: rajeev-atla
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # microdotblog: 
    # keybase: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

    # GitLab instances
    # gitlab:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up

markdown: kramdown

# Build settings
theme: minima

plugins:
 - jekyll-seo-tag
 - jemoji
 - jekyll-feed
 - jekyll-sitemap
 - jekyll-pdf-embed
